### ISSUE TITLE
taking screenshots of failed steps with chimp

### ISSUE THREAD

**Issue by Alino** [xolvio/automated-testing-best-practices#34]
please could you tell me, how should I tell chimp to take screenshots on circleCI?

I tried this in start.js

``` javascript
if (process.env.CIRCLECI) {
  chimpSwitches +=
  ' --screenshotsPath=' + path.resolve(process.env.CIRCLE_ARTIFACTS) + '/chrome' +
  ' --screenshotsOnError';
}
```

and this is how I call chimp in circle.yml

``` yaml
test:
  pre:
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber
  override:
    - mkdir -p $CIRCLE_ARTIFACTS/chrome
    - touch $CIRCLE_ARTIFACTS/chrome/something.txt

    # CHIMP CUCUMBER - Test the app with Chrome
    - cd app && npm run ci:
        environment:
          MONGO_URL: "mongodb://127.0.0.1:27018/kuknito"
          MONGO_OPLOG_URL: "mongodb://127.0.0.1:27018/local"
          CUCUMBER_JSON_OUTPUT: "$CIRCLE_TEST_REPORTS/cucumber/chrome.cucumber"
```

however screenshots won't get created and I don't know why :(
